version: 2
jobs:
    build:
      working_directory: ~/circleci-demo-python-django
      docker:
          - image: cimg/python:3.9.4

      steps:
          - checkout
          - run: python --version
          - run:
              command: |
                  sudo pip install pipenv
                  pipenv install -r pip-requirements.txt
          - run:
              command: |
                  pipenv run python manage.py test
